package discovery_test

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/nonchord/kcompass/internal/discovery"
)

// mockTXT returns a LookupTXT function that maps hostnames to TXT record slices.
func mockTXT(records map[string][]string) func(ctx context.Context, name string) ([]string, error) {
	return func(_ context.Context, name string) ([]string, error) {
		if recs, ok := records[name]; ok {
			return recs, nil
		}
		return nil, errors.New("no records")
	}
}

func TestDNSProbeFound(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"internal.company.com"},
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.internal.company.com": {"v=kc1; backend=https://github.com/company/clusters"},
		}),
	})
	b, err := probe(context.Background())
	require.NoError(t, err)
	require.NotNil(t, b)
	assert.Contains(t, b.Name(), "github.com")
}

func TestDNSProbeFoundGitSSH(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"corp.example.com"},
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.corp.example.com": {"v=kc1; backend=git@github.com:company/clusters"},
		}),
	})
	b, err := probe(context.Background())
	require.NoError(t, err)
	require.NotNil(t, b)
	assert.Contains(t, b.Name(), "github.com")
}

func TestDNSProbeNoMatchingDomain(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"example.com"},
		LookupTXT:     mockTXT(map[string][]string{}),
	})
	b, err := probe(context.Background())
	assert.NoError(t, err)
	assert.Nil(t, b)
}

func TestDNSProbeWrongTXTPrefix(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"example.com"},
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.example.com": {"v=spf1 include:_spf.google.com ~all"},
		}),
	})
	b, err := probe(context.Background())
	assert.NoError(t, err)
	assert.Nil(t, b)
}

func TestDNSProbeFirstDomainWins(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"first.com", "second.com"},
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.first.com":  {"v=kc1; backend=git@github.com:company/first"},
			"kcompass.second.com": {"v=kc1; backend=git@github.com:company/second"},
		}),
	})
	b, err := probe(context.Background())
	require.NoError(t, err)
	require.NotNil(t, b)
	assert.Contains(t, b.Name(), "first")
}

func TestDNSProbeLookupError(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"example.com"},
		LookupTXT: func(_ context.Context, _ string) ([]string, error) {
			return nil, errors.New("DNS timeout")
		},
	})
	b, err := probe(context.Background())
	assert.NoError(t, err)
	assert.Nil(t, b)
}

func TestDNSProbeEmptySearchDomains(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{},
		LookupTXT:     mockTXT(map[string][]string{}),
	})
	b, err := probe(context.Background())
	assert.NoError(t, err)
	assert.Nil(t, b)
}

func TestDNSProbeMultipleTXTRecords(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		SearchDomains: []string{"example.com"},
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.example.com": {
				"v=spf1 ...",
				"v=kc1; backend=git@github.com:company/clusters",
				"v=kc1; backend=git@github.com:company/other",
			},
		}),
	})
	b, err := probe(context.Background())
	require.NoError(t, err)
	require.NotNil(t, b)
	assert.Contains(t, b.Name(), "clusters")
}

func TestDNSProbeResolvConf(t *testing.T) {
	resolvConf := `
# Generated by NetworkManager
nameserver 1.1.1.1
search corp.example.com example.com
domain legacy.example.com
nameserver 8.8.8.8
`
	path := writeTempFile(t, resolvConf)

	var queried []string
	probe := discovery.DNSProbe(discovery.DNSOptions{
		ResolvConf: path,
		LookupTXT: func(_ context.Context, name string) ([]string, error) {
			queried = append(queried, name)
			return nil, errors.New("not found")
		},
	})

	_, err := probe(context.Background())
	require.NoError(t, err)

	assert.Contains(t, queried, "kcompass.corp.example.com")
	assert.Contains(t, queried, "kcompass.example.com")
	assert.Contains(t, queried, "kcompass.legacy.example.com")
}

func TestDNSProbeResolvConfFoundRecord(t *testing.T) {
	path := writeTempFile(t, "search internal.example.com\n")

	probe := discovery.DNSProbe(discovery.DNSOptions{
		ResolvConf: path,
		LookupTXT: mockTXT(map[string][]string{
			"kcompass.internal.example.com": {"v=kc1; backend=git@github.com:company/clusters"},
		}),
	})
	b, err := probe(context.Background())
	require.NoError(t, err)
	require.NotNil(t, b)
}

func TestDNSProbeMissingResolvConf(t *testing.T) {
	probe := discovery.DNSProbe(discovery.DNSOptions{
		ResolvConf: "/nonexistent/resolv.conf",
		LookupTXT: func(_ context.Context, _ string) ([]string, error) {
			return nil, errors.New("never called")
		},
	})
	b, err := probe(context.Background())
	assert.NoError(t, err)
	assert.Nil(t, b)
}

// --- parseTXTRecord edge cases via probe ---

func TestParseTXTRecordValid(t *testing.T) {
	cases := []string{
		"v=kc1; backend=https://github.com/company/clusters",
		"v=kc1;backend=git@github.com:company/clusters",
		"v=kc1 ; backend=https://github.com/company/clusters",
	}
	for _, input := range cases {
		t.Run(input, func(t *testing.T) {
			probe := discovery.DNSProbe(discovery.DNSOptions{
				SearchDomains: []string{"x.com"},
				LookupTXT: func(_ context.Context, _ string) ([]string, error) {
					return []string{input}, nil
				},
			})
			b, err := probe(context.Background())
			require.NoError(t, err)
			assert.NotNil(t, b, "expected backend for %q", input)
		})
	}
}

func TestParseTXTRecordInvalid(t *testing.T) {
	cases := []string{
		"",
		"v=spf1",
		"v=kc1",           // no backend field
		"v=kc1; backend=", // empty URL
		"backend=https://github.com/company/clusters", // missing v=kc1
	}
	for _, input := range cases {
		t.Run(input, func(t *testing.T) {
			probe := discovery.DNSProbe(discovery.DNSOptions{
				SearchDomains: []string{"x.com"},
				LookupTXT: func(_ context.Context, _ string) ([]string, error) {
					return []string{input}, nil
				},
			})
			b, err := probe(context.Background())
			assert.NoError(t, err)
			assert.Nil(t, b, "expected nil backend for %q", input)
		})
	}
}

func writeTempFile(t *testing.T, content string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "resolv*.conf")
	require.NoError(t, err)
	_, err = f.WriteString(content)
	require.NoError(t, err)
	require.NoError(t, f.Close())
	return f.Name()
}
